name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get CloudFlare Token
        run: echo ::set-env name=CLOUDFLARE_TOKEN::${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Get Test Domain Name
        run: echo ::set-env name=TEST_DOMAIN::${{ secrets.TEST_DOMAIN }}

      - name: Test and Build
        run: make test all shasums

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/cloudflare-ddns-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish to Docker Hub
        run: make docker-publish
