name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get uname
        run: echo ::set-env name=UNAME::$(uname)
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Results
          comment_title: Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          files: dist/test-results-${{ env.UNAME }}.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
